
# Copy the directory containing the theme to the remote servers themes directory
- name: Copy theme to server
  copy: dest="{{ tendenci_website_install_dir }}/themes/" src="{{ tendenci_custom_theme_name }}"

- name: Enable custom theme
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="set_theme {{ tendenci_custom_theme_name }}"
    # command: "python manage.py set_theme {{ tendenci_custom_theme_name }}"

