
- name: Install Django
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    virtualenv_python='python3'
    name="{{ tendenci_django_version }}"

- name: Create directory for logs
  file: state=directory path="{{ tendenci_website_log_dir }}" owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }}

- name: Create base website from template
  git:
    repo: "{{ tendenci_project_template }}"
    dest: "{{ tendenci_website_install_dir }}"
    update: no

- name: Install Tendenci dependencies
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    requirements={{ tendenci_website_install_dir }}/requirements/prod.txt
    extra_args="--upgrade --no-binary psycopg2"

# Load default theme
- name: Install default theme
  copy:
    remote_src: true
    src: "{{ tendenci_virtualenv_install_dir }}/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018/"
    dest: "{{ tendenci_website_install_dir }}/themes/tendenci2018"

# Stop here so the next taask group can happen - configuration

