
- name: Set DB connection user in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*USER'
    line: "DATABASES['default']['USER'] = '{{ tendenci_postgres_connection_user }}'"

- name: Set DB connection password in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*PASSWORD'
    line: "DATABASES['default']['PASSWORD'] = '{{ tendenci_postgres_connection_pass |mandatory }}'"

- name: Set DB name in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*NAME'
    line: "DATABASES['default']['NAME'] = '{{ tendenci_postgres_database_name }}'"

- name: Set Secret key
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^SECRET_KEY='.+'"
    line: "SECRET_KEY='{{ tendenci_site_secret_key |default( lookup('password', '/dev/null' )) }}'"

- name: Set Site settings key
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^SITE_SETTINGS_KEY='.+'"
    line: "SITE_SETTINGS_KEY='{{ tendenci_site_settings_key |default(lookup('password', '/dev/null' )) }}'"

- name: Change log folder
  replace: name="{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp="/var/log/mysite/" replace="{{ tendenci_website_log_dir }}/"

- name: Set Timezone
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^TIME_ZONE='.+'"
    line: "TIME_ZONE='{{ tendenci_time_zone }}'"

- name: Set allowed hosts
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^ALLOWED_HOSTS='.+'"
    line: "ALLOWED_HOSTS = {{ tendenci_allowed_hosts }}"

