---
# defaults file for tendenci

# Tendenci roles at the top, third party below.
######################################################
# Name of this tendenci install, used in filesystem paths and postgresql table names
tendenci_install_name: "tendenci"
# For example these paths use it for cooinstallability but you can choose different paths.
tendenci_virtualenv_install_dir: "/srv/{{ tendenci_install_name }}/environment"
tendenci_website_install_dir: "/srv/{{ tendenci_install_name }}/website"
tendenci_website_log_dir: "/srv/{{ tendenci_install_name }}/logs"

# Django version
tendenci_django_version: "Django>=1.11,<2.0"

# Tendenci base project
tendenci_project_template: 'https://github.com/tendenci/tendenci-project-template.git'

# Password will be encrypted by postgresql during user creation
tendenci_postgres_connection_user: "tendenci"
tendenci_postgres_connection_pass: ""
tendenci_postgres_database_name:   "{{ tendenci_install_name }}_db"

# Tendenci recommend that these be > 50 characters; if left blank one will be
# generated for you.
tendenci_site_secret_key: ""
tendenci_site_settings_key: ""

# Details of the first administrator/superuser account
tendenci_site_administrator_username: "admin"
tendenci_site_administrator_email: "admin@example.com"
# As with keys, user should override.
tendenci_site_administrator_password: "admin"

# DNS name of server
tendenci_server_visible_name: localhost
tendenci_server_visible_port: 80

# Where django will bind to, note that this is an internal address and
# users see the _server_visible_* values above.
tendenci_bind_address: 127.0.0.1
tendenci_bind_port: 8000

# If you have a custom theme, put its name here
tendenci_custom_theme_name: ""

# User and group for the daemons to run as
tendenci_run_as_user: www-data
tendenci_run_as_group: www-data

# Time for clock
tendenci_time_zone: 'Australia/Hobart'

# Python list of hosts allowed access.
# In a test environment this can be an external hostname; once properly
# deployed it should be localhost
tendenci_allowed_hosts: "['127.0.0.1']"

######################################################

